name: "Bug report"
description: "Report a bug or unexpected behavior."
title: "[Bug] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug 🙏
        Please provide the information below so we can help you faster.

  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Describe the bug clearly.
      placeholder: "The library crashes when calling X with Y."
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What did you expect to happen?
      placeholder: "The function should return a valid result."
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      description: Minimal steps or code to reproduce the issue.
      placeholder: |
        1. Install the library
        2. Call function X
        3. See error
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Provide relevant environment details.
      placeholder: |
        - OS:
        - Runtime / Language version:
        - Library version:
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Error logs / stack trace
      render: shell
      placeholder: "Paste error output here"
    validations:
      required: false
