name: "New linter rule"
description: "Suggest adding a new linting rule."
title: "[Rule] "
labels: ["enhancement", "linter"]
body:
  - type: markdown
    attributes:
      value: |
        Use this template to suggest a new linting rule.

  - type: textarea
    id: description
    attributes:
      label: Rule description
      description: What should the rule enforce?
      placeholder: "Require commit messages to follow Conventional Commits."
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Why is this rule needed?
      description: What problem does it solve?
      placeholder: "Helps keep commit history consistent and readable."
    validations:
      required: true

  - type: textarea
    id: examples
    attributes:
      label: Examples
      description: Provide examples of valid and invalid cases.
      placeholder: |
        ✅ feat(api): add pagination
        ❌ added pagination
    validations:
      required: true

  - type: textarea
    id: configuration
    attributes:
      label: Configuration (optional)
      description: Optional configuration or parameters for the rule.
      placeholder: |
        allowedTypes:
          - feat
          - fix
          - docs
    validations:
      required: false

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      options:
        - Error (block)
        - Warning (non-blocking)
    validations:
      required: true

  - type: textarea
    id: notes
    attributes:
      label: Additional context
      placeholder: "Should not apply to auto-generated commits."
    validations:
      required: false
